# Java SimpleDateFormat (https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/text/SimpleDateFormat.html)
date-format: EEE, d MMM y, HH:mm

# BCP 47 format (https://www.techonthenet.com/js/language_tags.php) 
date-locale: en-US

# Refresh interval is in milliseconds. It must be divisible by 50.
refresh-interval: 950
